//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_t_function
    {
        public string ID { get; set; }
        public string PID { get; set; }
        public string FunctionName { get; set; }
        public string Url { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public int Visible { get; set; }
    }
}
