//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarmdetail
    {
        public string AlarmDetail_ID { get; set; }
        public string Train_ID { get; set; }
        public string TrainDetail_ID { get; set; }
        public string Side { get; set; }
        public string FileName { get; set; }
        public string FileContent { get; set; }
        public string ProblemType { get; set; }
        public Nullable<int> AlarmLevel { get; set; }
        public string Source { get; set; }
        public Nullable<int> AlgResult { get; set; }
        public string HandleResult { get; set; }
        public string OpUser { get; set; }
        public Nullable<System.DateTime> OpTime { get; set; }
        public System.DateTime InsertTime { get; set; }
    }
}
