//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class line
    {
        public int Line_ID { get; set; }
        public string Line_Name { get; set; }
        public string GQCode { get; set; }
        public string CXCode { get; set; }
        public string WMVCode { get; set; }
        public string IPaddress { get; set; }
        public string Userid { get; set; }
        public string Pass { get; set; }
        public string port { get; set; }
        public string CameNum { get; set; }
        public string TelexCode { get; set; }
        public string NextTelexCode { get; set; }
    }
}
