//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qbdetail
    {
        public string QBDetailID { get; set; }
        public string QBMasterID { get; set; }
        public string CC { get; set; }
        public string SWBZ { get; set; }
        public string CH { get; set; }
        public string SWH { get; set; }
        public string CZ { get; set; }
        public string CX { get; set; }
        public string PM { get; set; }
        public string JS { get; set; }
        public string PB { get; set; }
        public string JYBZ { get; set; }
        public System.DateTime Intime { get; set; }
    }
}
