//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TOEC_Common;

    public partial class sartasEntities : DbContext
    {
        public sartasEntities()
            : base(Config.ConStr_EF_SASTAD)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<alarmdetail> alarmdetail { get; set; }
        public virtual DbSet<hotwheel_axle> hotwheel_axle { get; set; }
        public virtual DbSet<line> line { get; set; }
        public virtual DbSet<qbdetail> qbdetail { get; set; }
        public virtual DbSet<qbmaster> qbmaster { get; set; }
        public virtual DbSet<sys_code> sys_code { get; set; }
        public virtual DbSet<sys_codemap> sys_codemap { get; set; }
        public virtual DbSet<train> train { get; set; }
        public virtual DbSet<traindetail> traindetail { get; set; }
        public virtual DbSet<sys_log> sys_log { get; set; }
        public virtual DbSet<account_r_role_function> account_r_role_function { get; set; }
        public virtual DbSet<account_r_users_roles> account_r_users_roles { get; set; }
        public virtual DbSet<account_t_function> account_t_function { get; set; }
        public virtual DbSet<account_t_role> account_t_role { get; set; }
        public virtual DbSet<account_t_station> account_t_station { get; set; }
        public virtual DbSet<account_t_user> account_t_user { get; set; }
        public virtual DbSet<statistics_image> statistics_image { get; set; }
    }
}
