//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistics_image
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TrainID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> AllCarNum { get; set; }
        public Nullable<int> OneCarCheckImagesNums { get; set; }
        public Nullable<System.DateTime> TrainComeDate { get; set; }
        public Nullable<int> StaggerBgnOrderNo { get; set; }
        public Nullable<int> StaggerEndOrderNo { get; set; }
        public Nullable<int> MonitorImageNum { get; set; }
        public Nullable<int> CallAlgImageNum { get; set; }
        public Nullable<int> SucCheckImageNum { get; set; }
        public Nullable<int> FailCheckImageNum { get; set; }
        public Nullable<int> NoCheckImageNum { get; set; }
        public string MonitorImageRemark { get; set; }
        public string CallAlgImageRemark { get; set; }
        public string SucCheckImageRemark { get; set; }
        public string FailCheckImageRemark { get; set; }
        public string NoCheckImageRemark { get; set; }
        public Nullable<int> RecvCarInfoNum { get; set; }
        public Nullable<int> UseQBCarInfoNum { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
