//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_code
    {
        public int Code_ID { get; set; }
        public string CodeMap_ID { get; set; }
        public Nullable<int> tabindex { get; set; }
        public string Code { get; set; }
        public string Meaning { get; set; }
        public string Remark { get; set; }
        public string IsEnable { get; set; }
    }
}
