//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class train
    {
        public System.Guid Train_ID { get; set; }
        public Nullable<int> Line_ID { get; set; }
        public string Train_No { get; set; }
        public string Train_Speed { get; set; }
        public Nullable<int> Train_Count { get; set; }
        public string Train_type { get; set; }
        public Nullable<System.DateTime> Train_ComeDate { get; set; }
        public int Train_WorkFlag { get; set; }
        public Nullable<int> Train_Real { get; set; }
        public string source { get; set; }
        public string TelexCode { get; set; }
        public string AlarmLevel { get; set; }
    }
}
