//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_SASTAD_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class traindetail
    {
        public System.Guid TrainDetail_ID { get; set; }
        public Nullable<System.Guid> Train_ID { get; set; }
        public Nullable<int> TrainDetail_OrderNo { get; set; }
        public string TrainDetail_No { get; set; }
        public string TrainDetail_Remark { get; set; }
        public Nullable<int> TrainDetail_IF { get; set; }
        public string vehicletype { get; set; }
        public string startstation { get; set; }
        public string endstation { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> Ziz { get; set; }
        public Nullable<decimal> Zaiz { get; set; }
        public Nullable<decimal> HC { get; set; }
        public string smoke_result { get; set; }
        public Nullable<System.DateTime> DealTime { get; set; }
        public string AlarmLevel { get; set; }
        public Nullable<System.DateTime> AlarmTime { get; set; }
    }
}
